name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Building QuickJS
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        persist-credentials: false
        fetch-depth: 0

    - name: Build Linux x64
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo rm -rf libs/qjs_linux_x64.a
        sudo mkdir build
        sudo cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S ./ -B ./build
        sudo cmake --build ./build --config Release
        sudo cp build/libqjs.a libs/qjs_linux_x64.a
        sudo rm -rf build
        sudo rm -rf libs/include
        sudo mkdir libs/include
        sudo cp quickjs/quickjs.h libs/include/quickjs.h
        sudo cp quickjs/quickjs-libc.h libs/include/quickjs-libc.h
    - name: Create PR For Linux x64 
      if: matrix.platform == 'ubuntu-latest'
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update Linux x64 & C Headers
        branch-suffix: random
        delete-branch: true
        title: Update Linux x64 & C Headers

    - name: Build Macos x64
      if: matrix.platform == 'macos-latest'
      run: |
        sudo rm -rf libs/qjs_macos_x64.a
        sudo mkdir ./build
        sudo cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -S ./ -B ./build
        sudo cmake --build ./build --config Release
        sudo cp build/libqjs.a libs/qjs_macos_x64.a
        sudo rm -rf build
    - name: Create PR For Macos x64 
      if: matrix.platform == 'macos-latest'
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update Macos x64
        branch-suffix: random
        delete-branch: true
        title: Update Macos x64
    
    - name: Prepare Windows x64
      if: matrix.platform == 'windows-latest'
      shell: cmd
      run: setx PATH "%PATH%;C:\msys64\mingw64\bin"
    - name: Build Windows x64
      if: matrix.platform == 'windows-latest'
      shell: bash
      run: |
        rm -rf ./libs/qjs_win_x64.a
        mkdir ./build
        cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build
        cmake --build ./build --config Release
        cp build/libqjs.a libs/qjs_win_x64.a
        rm -rf ./build
    - name: Create PR For Windows x64 
      if: matrix.platform == 'windows-latest'
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Update Windows x64
        branch-suffix: random
        delete-branch: true
        title: Update Windows x64