name: Test

on:
  workflow_dispatch:

# on:
#   push:
#     branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
      fail-fast: true
    steps:
      - name: Setup V
        uses: vlang/setup-v@v1.4
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v4

      - name: Verify fmt
        run: |
          v fmt -diff .
          v fmt -verify .

      - name: Run Tests Linux and Mac
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: v test .

      - name: Run Tests Windows
        if: matrix.os == 'windows-latest'
        run: v -cc gcc test .